

DROP TABLE IF EXISTS `webtoffee_wc_admin_notes` ;/*END*/ 

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";/*END*/
SET time_zone = "+00:00";/*END*/


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;/*END*/
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;/*END*/
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;/*END*/
/*!40101 SET NAMES utf8 */;/*END*/
--
-- Database: `websitedonasi`
--




CREATE TABLE `webtoffee_wc_admin_notes` (
  `note_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locale` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_data` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date_created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_reminder` datetime DEFAULT NULL,
  `is_snoozable` tinyint(1) NOT NULL DEFAULT 0,
  `layout` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `icon` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'info',
  PRIMARY KEY (`note_id`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;/*END*/


INSERT INTO `webtoffee_wc_admin_notes` VALUES
("1","new_in_app_marketplace_2021","info","en_US","Customize your store with extensions","Check out our NEW Extensions tab to see our favorite extensions for customizing your store, and discover the most popular extensions in the WooCommerce Marketplace.","{}","unactioned","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("2","wayflyer_bnpl_q4_2021","marketing","en_US","Grow your business with funding through Wayflyer","Fast, flexible financing to boost cash flow and help your business grow – one fee, no interest rates, penalties, equity, or personal guarantees. Based on your store’s performance, Wayflyer provides funding and analytical insights to invest in your business.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("3","wc_shipping_mobile_app_usps_q4_2021","marketing","en_US","Print and manage your shipping labels with WooCommerce Shipping and the WooCommerce Mobile App","Save time by printing, purchasing, refunding, and tracking shipping labels generated by <a href=\"https://woocommerce.com/woocommerce-shipping/\">WooCommerce Shipping</a> – all directly from your mobile device!","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("4","wc_shipping_mobile_app_q4_2021","marketing","en_US","Print and manage your shipping labels with the WooCommerce Mobile App","Save time by printing, purchasing, refunding, and tracking shipping labels generated by <a href=\"https://woocommerce.com/woocommerce-shipping/\">WooCommerce Shipping</a> – all directly from your mobile device!","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("5","ecomm-need-help-setting-up-your-store","info","en_US","Need help setting up your Store?","Schedule a free 30-min <a href=\"https://wordpress.com/support/concierge-support/\">quick start session</a> and get help from our specialists. We’re happy to walk through setup steps, show you around the WordPress.com dashboard, troubleshoot any issues you may have, and help you the find the features you need to accomplish your goals for your site.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("6","woocommerce-services","info","en_US","WooCommerce Shipping & Tax","WooCommerce Shipping &amp; Tax helps get your store \"ready to sell\" as quickly as possible. You create your products. We take care of tax calculation, payment processing, and shipping label printing! Learn more about the extension that you just installed.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("7","ecomm-unique-shopping-experience","info","en_US","For a shopping experience as unique as your customers","Product Add-Ons allow your customers to personalize products while they\'re shopping on your online store. No more follow-up email requests—customers get what they want, before they\'re done checking out. Learn more about this extension that comes included in your plan.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("8","wc-admin-getting-started-in-ecommerce","info","en_US","Getting Started in eCommerce - webinar","We want to make eCommerce and this process of getting started as easy as possible for you. Watch this webinar to get tips on how to have our store up and running in a breeze.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("9","your-first-product","info","en_US","Your first product","That’s huge! You’re well on your way to building a successful online store — now it’s time to think about how you’ll fulfill your orders.<br /><br />Read our shipping guide to learn best practices and options for putting together your shipping strategy. And for WooCommerce stores in the United States, you can print discounted shipping labels via USPS with <a href=\"https://href.li/?https://woocommerce.com/shipping\" target=\"_blank\">WooCommerce Shipping</a>.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("10","wc-admin-optimizing-the-checkout-flow","info","en_US","Optimizing the checkout flow","It’s crucial to get your store’s checkout as smooth as possible to avoid losing sales. Let’s take a look at how you can optimize the checkout experience for your shoppers.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("11","wc-admin-first-five-things-to-customize","info","en_US","The first 5 things to customize in your store","Deciding what to start with first is tricky. To help you properly prioritize, we’ve put together this short list of the first few things you should customize in WooCommerce.","{}","unactioned","woocommerce.com","2022-04-05 17:00:18","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("12","wc-payments-qualitative-feedback","info","en_US","WooCommerce Payments setup - let us know what you think","Congrats on enabling WooCommerce Payments for your store. Please share your feedback in this 2 minute survey to help us improve the setup process.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("13","share-your-feedback-on-paypal","info","en_US","Share your feedback on PayPal","Share your feedback in this 2 minute survey about how we can make the process of accepting payments more useful for your store.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("14","google_listings_and_ads_install","marketing","en_US","Drive traffic and sales with Google","Reach online shoppers to drive traffic and sales for your store by showcasing products across Google, for free or with ads.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("15","wc-subscriptions-security-update-3-0-15","info","en_US","WooCommerce Subscriptions security update!","We recently released an important security update to WooCommerce Subscriptions. To ensure your site’s data is protected, please upgrade <strong>WooCommerce Subscriptions to version 3.0.15</strong> or later.<br /><br />Click the button below to view and update to the latest Subscriptions version, or log in to <a href=\"https://woocommerce.com/my-dashboard\">WooCommerce.com Dashboard</a> and navigate to your <strong>Downloads</strong> page.<br /><br />We recommend always using the latest version of WooCommerce Subscriptions, and other software running on your site, to ensure maximum security.<br /><br />If you have any questions we are here to help — just <a href=\"https://woocommerce.com/my-account/create-a-ticket/\">open a ticket</a>.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("16","woocommerce-core-update-5-4-0","info","en_US","Update to WooCommerce 5.4.1 now","WooCommerce 5.4.1 addresses a checkout issue discovered in WooCommerce 5.4. We recommend upgrading to WooCommerce 5.4.1 as soon as possible.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("17","wcpay-promo-2020-11","marketing","en_US","wcpay-promo-2020-11","wcpay-promo-2020-11","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("18","wcpay-promo-2020-12","marketing","en_US","wcpay-promo-2020-12","wcpay-promo-2020-12","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("19","ppxo-pps-upgrade-paypal-payments-1","info","en_US","Get the latest PayPal extension for WooCommerce","Heads up! There’s a new PayPal on the block!<br /><br />Now is a great time to upgrade to our latest <a href=\"https://woocommerce.com/products/woocommerce-paypal-payments/\" target=\"_blank\">PayPal extension</a> to continue to receive support and updates with PayPal.<br /><br />Get access to a full suite of PayPal payment methods, extensive currency and country coverage, and pay later options with the all-new PayPal extension for WooCommerce.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("20","ppxo-pps-upgrade-paypal-payments-2","info","en_US","Upgrade your PayPal experience!","Get access to a full suite of PayPal payment methods, extensive currency and country coverage, offer subscription and recurring payments, and the new PayPal pay later options.<br /><br />Start using our <a href=\"https://woocommerce.com/products/woocommerce-paypal-payments/\" target=\"_blank\">latest PayPal today</a> to continue to receive support and updates.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("21","woocommerce-core-sqli-july-2021-need-to-update","update","en_US","Action required: Critical vulnerabilities in WooCommerce","In response to a critical vulnerability identified on July 13, 2021, we are working with the WordPress Plugins Team to deploy software updates to stores running WooCommerce (versions 3.3 to 5.5) and the WooCommerce Blocks feature plugin (versions 2.5 to 5.5).<br /><br />Our investigation into this vulnerability is ongoing, but <strong>we wanted to let you know now about the importance of updating immediately</strong>.<br /><br />For more information on which actions you should take, as well as answers to FAQs, please urgently review our blog post detailing this issue.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("22","woocommerce-blocks-sqli-july-2021-need-to-update","update","en_US","Action required: Critical vulnerabilities in WooCommerce Blocks","In response to a critical vulnerability identified on July 13, 2021, we are working with the WordPress Plugins Team to deploy software updates to stores running WooCommerce (versions 3.3 to 5.5) and the WooCommerce Blocks feature plugin (versions 2.5 to 5.5).<br /><br />Our investigation into this vulnerability is ongoing, but <strong>we wanted to let you know now about the importance of updating immediately</strong>.<br /><br />For more information on which actions you should take, as well as answers to FAQs, please urgently review our blog post detailing this issue.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("23","woocommerce-core-sqli-july-2021-store-patched","update","en_US","Solved: Critical vulnerabilities patched in WooCommerce","In response to a critical vulnerability identified on July 13, 2021, we worked with the WordPress Plugins Team to deploy software updates to stores running WooCommerce (versions 3.3 to 5.5) and the WooCommerce Blocks feature plugin (versions 2.5 to 5.5).<br /><br /><strong>Your store has been updated to the latest secure version(s)</strong>. For more information and answers to FAQs, please review our blog post detailing this issue.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("24","woocommerce-blocks-sqli-july-2021-store-patched","update","en_US","Solved: Critical vulnerabilities patched in WooCommerce Blocks","In response to a critical vulnerability identified on July 13, 2021, we worked with the WordPress Plugins Team to deploy software updates to stores running WooCommerce (versions 3.3 to 5.5) and the WooCommerce Blocks feature plugin (versions 2.5 to 5.5).<br /><br /><strong>Your store has been updated to the latest secure version(s)</strong>. For more information and answers to FAQs, please review our blog post detailing this issue.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("25","habit-moment-survey","marketing","en_US","We’re all ears! Share your experience so far with WooCommerce","We’d love your input to shape the future of WooCommerce together. Feel free to share any feedback, ideas or suggestions that you have.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("26","ecomm-wc-navigation-survey","info","en_US","We’d like your feedback on the WooCommerce navigation","We’re making improvements to the WooCommerce navigation and would love your feedback. Share your experience in this 2 minute survey.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("27","lead_gen_existing_customers_1","marketing","en_US","Talk to a consultant","As your business grows, you want to optimize costs, streamline operations, and sell more. We can help. Talk to us about how you can get the most out of WooCommerce.","{}","unactioned","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("28","woocommerce-core-paypal-march-2022-updated","update","en_US","Security auto-update of WooCommerce","<strong>Your store has been updated to the latest secure version of WooCommerce</strong>. We worked with WordPress to deploy PayPal Standard security updates for stores running WooCommerce (version 3.5 to 6.3). It’s recommended to disable PayPal Standard, and use <a href=\"https://woocommerce.com/products/woocommerce-paypal-payments/\" target=\"_blank\">PayPal Payments</a> to accept PayPal.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("29","woocommerce-core-paypal-march-2022-updated-nopp","update","en_US","Security auto-update of WooCommerce","<strong>Your store has been updated to the latest secure version of WooCommerce</strong>. We worked with WordPress to deploy security updates related to PayPal Standard payment gateway for stores running WooCommerce (version 3.5 to 6.3).","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("30","pinterest_03_2022_update","marketing","en_US","Your Pinterest for WooCommerce plugin is out of date!","Update to the latest version of Pinterest for WooCommerce to continue using this plugin and keep your store connected with Pinterest. To update, visit <strong>Plugins &gt; Installed Plugins</strong>, and click on “update now” under Pinterest for WooCommerce.","{}","pending","woocommerce.com","2022-04-03 09:58:08","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("31","surface_cart_checkout","info","en_US","Memperkenalkan blok Keranjang dan Checkout!","Tingkatkan pendapatan toko Anda menggunakan blok Keranjang &amp; Checkout WooCommerce dengan pengoptimalan konversi, tersedia di ekstensi Blok WooCommerce.","{}","unactioned","woo-gutenberg-products-block","2022-04-03 09:58:09","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("32","wc-admin-wc-helper-connection","info","en_US","Sambungkan ke WooCommerce.com","Sambungkan untuk mendapatkan pemberitahuan dan pembaruan produk penting.","{}","unactioned","woocommerce-admin","2022-04-03 09:58:10","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("33","wc-admin-complete-store-details","info","en_US","Tambahkan detail toko untuk menyelesaikan penyiapan toko","Lengkapi detail toko Anda dengan informasi penting pada penyiapan seperti alamat basis toko","{}","unactioned","woocommerce-admin","2022-04-03 09:58:10","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("34","wc-admin-choosing-a-theme","marketing","en_US","Memilih tema?","Periksa tema yang kompatibel dengan WooCommerce dan pilih tema yang sesuai dengan kebutuhan merek dan bisnis Anda.","{}","unactioned","woocommerce-admin","2022-04-04 10:41:15","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("35","wc-admin-insight-first-product-and-payment","survey","en_US","Wawasan","Lebih dari 80% penjual baru menambahkan produk pertama dan menyiapkan setidaknya satu metode pembayaran pada minggu pertama.<br><br>Apakah menurut Anda tipe wawasan ini bermanfaat?","{}","unactioned","woocommerce-admin","2022-04-04 10:41:15","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("36","wc-admin-customizing-product-catalog","info","en_US","Cara menyesuaikan katalog produk Anda","Anda pasti ingin katalog produk dan gambar terlihat bagus dan sesuai dengan merek Anda. Panduan ini akan memberikan semua tips yang diperlukan agar produk Anda tampil keren di toko.","{}","unactioned","woocommerce-admin","2022-04-04 10:41:15","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("37","wc-admin-mobile-app","info","en_US","Instal aplikasi seluler Woo","Instal aplikasi seluler WooCommerce untuk mengelola pesanan, menerima pemberitahuan penjualan, dan melihat metrik kunci — di mana pun Anda berada.","{}","unactioned","woocommerce-admin","2022-04-05 17:00:17","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("38","wc-admin-usage-tracking-opt-in","info","en_US","Bantu WooCommerce menjadi lebih baik dengan pelacakan penggunaan","Mengumpulkan data penggunaan memungkinkan kami meningkatkan WooCommerce. Toko Anda akan dipertimbangkan selagi kami mengevaluasi fitur baru, menilai kualitas pembaruan, atau menentukan apakah sebuah pembaruan masuk akal. Anda selalu dapat mengunjungi <a href=\"http://localhost/websitedonasi/wp-admin/admin.php?page=wc-settings&#038;tab=advanced&#038;section=woocommerce_com\" target=\"_blank\">Pengaturan</a> dan memilih untuk berhenti berbagi data. <a href=\"https://woocommerce.com/usage-tracking?utm_medium=product\" target=\"_blank\">Baca selengkapnya</a> tentang data yang kami kumpulkan.","{}","unactioned","woocommerce-admin","2022-04-11 16:43:12","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("39","wc-admin-onboarding-payments-reminder","info","en_US","Mulai menerima pembayaran di toko Anda!","Ambil pembayaran dengan penyedia yang cocok dengan Anda - pilih dari 100+ gerbang pembayaran untuk WooCommerce.","{}","unactioned","woocommerce-admin","2022-04-11 16:43:12","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("40","wc-admin-insight-first-sale","survey","en_US","Tahukah Anda?","Toko berbasis WooCommerce membutuhkan rata-rata 31 hari untuk mendapatkan penjualan pertama. Pilihan Anda sudah tepat! Apakah menurut Anda tipe wawasan ini bermanfaat?","{}","unactioned","woocommerce-admin","2022-04-11 16:43:12","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("41","setup_task_initiative_survey_q2_2022","survey","en_US","We want to know what matters most to you","Take 2 minutes to give us your input on what is important for you while setting up your store and help shape the future of WooCommerce together.","{}","unactioned","woocommerce.com","2022-05-10 09:29:56","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("42","woocommerce_payments_subscriptions_nopayments_q2_2022","marketing","en_US","Sell subscriptions online – without a paid extension","Say hello to WooCommerce Payments – now with built-in subscriptions functionality. Get free access to the features you need to start earning recurring revenue online. Pay as you go, with no setup costs or monthly fees.","{}","pending","woocommerce.com","2022-05-10 09:29:56","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("43","woocommerce_payments_subscriptions_yespayments_q2_2022","marketing","en_US","Sell subscriptions online – no extra extension required","It\'s here! WooCommerce Payments now features built-in subscriptions functionality. No need to install an extra, paid extension – we\'ve made it simpler than ever to start earning recurring revenue. Ready to grow your business?","{}","pending","woocommerce.com","2022-05-10 09:29:56","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("44","setup_task_second_survey_q2_2022","survey","en_US","We want to know what matters most to you","Take 2 minutes to give us your input on what is important for you while setting up your store and help shape the future of WooCommerce together.","{}","pending","woocommerce.com","2022-05-10 09:29:56","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("45","store_setup_survey_survey_q2_2022","survey","en_US","How is your store setup going?","Our goal is to make sure you have all the right tools to start setting up your store in the smoothest way possible.
We’d love to know if we hit our mark and how we can improve. To collect your thoughts, we made a 2-minute survey.","{}","pending","woocommerce.com","2022-05-10 09:29:56","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("46","affirm_q2_2022","marketing","en_US","Boost your business with flexible payments","Expand your customer base with smarter payment options for more shoppers. With Affirm,  you can offer the most relevant payment options at every price point – from four interest-free payments every two weeks to longer installments up to 36 months. Fast-track your revenue goals today!","{}","pending","woocommerce.com","2022-05-20 07:03:42","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("47","wc-admin-EU-consumer-protection","marketing","en_US","Important changes to EU consumer protection laws","New regulations to help modernize and strengthen consumer protection laws in the European Union (EU) take effect on May 28, 2022. These rules impact all merchants selling to the EU, regardless of where their business is located. Further detailed information is available on the European Commission\'s official website.","{}","unactioned","woocommerce.com","2022-05-20 07:03:42","","0","plain","","0","0","info");/*END*/
INSERT INTO `webtoffee_wc_admin_notes` VALUES
("48","googlelistings_multicountrygtm_q22022","marketing","en_US","Expand your audience with Multi-Country Advertising","It\'s time to expand your audience with Multi-Country Advertising, an exciting new feature in Google Listings &amp; Ads. Reach more potential customers in as many regions as you like within a single campaign, all from the convenience of your WooCommerce dashboard.","{}","unactioned","woocommerce.com","2022-05-20 07:03:42","","0","plain","","0","0","info");/*END*/